### ISSUE TITLE
Setup code style checking in CI

### ISSUE THREAD

**Issue by evelikov** [kmod-project/kmod#88]
The in-tree code-style guide is great, but ideally the topic should be automated. Since the goal is to follow the kernel style, we can reuse the [clang-format](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/.clang-format?h=v6.11-rc5) setup.

Running the ^^ config against the master branch shows, a notable diff stat. Should we address that in-part before/alongside/after the CI action?
 
```
 57 files changed, 2146 insertions(+), 1892 deletions(-)
```

Glancing through the dozen+ of github actions, my personal preference is https://github.com/yshui/git-clang-format-lint/ ... and we'd want to set `input.base` to `GITHUB_BASE_REF` over the default is `HEAD^`.

**Comment by lucasdemarchi** [comment]
doing a quick run here... I think a good portion of the diff is because of alignment when breaking a new line.
When kmod started it actually followed BlueZ's coding style, that is (was?) slightly different than kernel's.  I don't mind, or better, I actually prefer, following a plain kernel's style as it's actually what I and other contributors most used to nowadays. 

We have to add a few foreach macros in the config: kmod_list_foreach, kmod_list_foreach_reverse. clang-format also fixes some stuff in a less than ideal way:

```diff
        if (ctx == NULL)
-               return NULL;;
+               return NULL;
+       ;
```

We obviously don't need an empty statement there.

```diff
-KMOD_EXPORT const char *kmod_config_iter_get_key(const struct kmod_config_iter *iter)
+KMOD_EXPORT const char *
+kmod_config_iter_get_key(const struct kmod_config_iter *iter)
```

Don't really like the type split since then it's not visible in grep. Can we disable that?

```diff
+static _always_inline_
+       _printf_format_(2, 3) void kmod_log_null(const struct kmod_ctx *ctx,
+                                                const char *format, ...)
```

not sure what happened here... maybe it didn't understand the attr? Same thing in other places with attributes.

Other changes look sane.
